version: '3'

services:

  postgres-db-security:
    image: postgres:12-alpine
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_MULTIPLE_DATABASES: "security"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456

  auth-service:
    build:
      context: ../
      dockerfile: Dockerfile
    image: security-jwt/application
    restart: always
    ports:
      - 8080:8080
    environment:
      DB_URL: "jdbc:postgresql://postgres-db-security:5432/security"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "123456"
